# syntax=docker/dockerfile:1
# легковесный линукс с питоном
FROM python:3.10-alpine
WORKDIR /code
# переменные окружения
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
# ставим зависимости
RUN pip install -r requirements.txt
# заметка для админа, какой порт потом надо публиковать
EXPOSE 5000
# копируем из текущего каталога в workdir
COPY app.py .
# запускаем flask
CMD ["flask", "run", "--debug"]

